import  java.util.Scanner;
public class solution {

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
       String n =sc.nextLine();
      int  count =0;
      for(int i=0;i<n.length();i++)
      {
          if(n.charAt(i)=='4'||n.charAt(i)=='7') count++;
          if(count>7)
          {
              System.out.println("NO");
              return;
          }

      }
      if(count==4||count==7)
      {
          System.out.println("YES");
      }
      else
      {
          System.out.println("NO");
      }

    }
}
